Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import scipy.stats

races = ["Black, non-Hispanic", "White, non-Hispanic", "Hispanic", "Other, non-Hispanic"]
for i in range(len(races)):
    for j in range(i, len(races)):
        race1, race2 = races[i], races[j]
        if race1 != race2:
            print(race1, race2, scipy.stats.ttest_ind(multitest_ca[multitest_ca["Stratification1"] == race1]["DataValue"],
                      multitest_ca[multitest_ca["Stratification1"] == race2]["DataValue"], axis=0, equal_var=False))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[10], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstats[39;00m
[1;32m      3[0m races [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mBlack, non-Hispanic[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mWhite, non-Hispanic[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mHispanic[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mOther, non-Hispanic[39m[38;5;124m"[39m]
[1;32m      4[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(races)):

[0;31mModuleNotFoundError[0m: No module named 'scipy'

